// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "../drivers/gpio_driver/gpio_driver.h"
#define NODE_LED DT_ALIAS(led0)

static struct gpio_dt_spec led = GPIO_DT_SPEC_GET(NODE_LED, gpios);

gpio_driver_t *led_driver;
bool led_state = true;
uint8_t is_init = 0;

void toggle_led(lv_event_t * e)
{
	if (is_init == 0)
	{
		led_driver = GPIO_DRIVER_Create(&led);
		led_driver->config_output(led_driver);
		is_init = 1;
	}
	
	if(led_state == true)
		led_driver->set(led_driver);
	else
		led_driver->reset(led_driver);
	led_state = !led_state;
}
